config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'logging/index', as: :logging
  post 'logging/info'
  post 'logging/debug'
  post 'logging/with_procname'
  post 'logging/with_procname_hash'
  post 'logging/tagged'
  post 'logging/multi_tagged'

  get 'exceptions/index', as: :exceptions
  post 'exceptions/trigger', as: :trigger_exception

  get 'webpush/index', as: :webpush
  post 'webpush/trigger', as: :webpush_trigger

  get 'widgets/chat', as: :chat
  get 'widgets/arcud', as: :arcud
  #get 'widgets/notifications', as: :notifications

  resources :articles
  resources :candidates, only: [:index] do
    collection do
      put :reset_votes_for
    end
    member do
      put :vote
    end
  end

  root to: "home#index", as: :home
  get 'manifest.json', to: redirect(ActionController::Base.helpers.asset_path('manifest.json'))
  get 'firebase-messaging-sw.js', to: -> (env) do
    [200, { 'Content-Type' => 'application/javascript' }, [Rails.application.assets_manifest.find_sources('firebase-messaging-sw.js').first]]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  binnacle_signal on: [:create, :update, :destroy]
end

app/models/candidate.rb
class Candidate < ApplicationRecord
  acts_as_votable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessor :login

  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :update, :destroy]

  respond_to :js

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.save
  end

  def update
    @article.update(article_params)
  end

  def destroy
    @article.destroy

    render nothing: true
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController

  respond_to :js, except: :index

  def index
    @candidates = Candidate.all
  end

  def vote
    candidate = Candidate.find(params[:id])
    candidate.liked_by current_user
    votes = Candidate.all.map { |c| [c.name, c.votes_for.size] }

    client = Binnacle::Client.new(ENV['BINNACLE_API_KEY'], ENV['BINNACLE_API_SECRET'])
    client.signal_asynch(ENV['BINNACLE_VOTING_CHANNEL'], 'VOTES',
                                               current_user.id,
                                               '',
                                               'INFO',
                                               [],
                                               votes)
  end

  def reset_votes_for
    current_user.votes.delete_all

    votes = Candidate.all.map { |c| [c.name, c.votes_for.size] }

    client = Binnacle::Client.new(ENV['BINNACLE_API_KEY'], ENV['BINNACLE_API_SECRET'])
    client.signal_asynch(ENV['BINNACLE_VOTING_CHANNEL'], 'VOTES',
                                               current_user.id,
                                               '',
                                               'INFO',
                                               [],
                                               votes)
  end

end

app/controllers/exceptions_controller.rb
class ExceptionsController < ApplicationController
  def index; end

  def trigger
    random_choice = 1 + rand(10)
    case random_choice
    when 1
      1 / 0
    when 2
      [1, 2, 3].first("two")
    when 3
      eval("1+1=2")
    when 4
      "hello".to_ary
    when 5
      [1, 2, 3].first(4, 5)
    when 6
      Float::INFINITY.to_r
    when 7
      puts foo
    when 8
      Regexp.new("?")
    when 9
      [1, 2, 3].drop(1 << 100)
    when 10
      h = {}
      h.fetch("baz") #=> KeyError: key not found: "baz"
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index; end
end

app/controllers/logging_controller.rb
class LoggingController < ApplicationController
  def index; end

  def info
    Binnacle.logger.info("This is an info message")
    render nothing: true
  end

  def debug
    Binnacle.logger.level = Logger::DEBUG
    Binnacle.logger.debug("This is an debug message")
    Binnacle.logger.level = Logger::INFO
    render nothing: true
  end

  def with_procname
    Binnacle.logger.level = Logger::ERROR
    Binnacle.logger.error('comm_error') { "Can't reach the service endpoint!" }
    Binnacle.logger.level = Logger::INFO
    render nothing: true
  end

  def with_procname_hash
    Binnacle.logger.info(channel_id: ENV['BINNACLE_APP_LOG_CHANNEL'], session_id: '8675309', event_name: 'failed_transfer') { 'transfer failed, bad RTN' }
    render nothing: true
  end

  def tagged
    Binnacle.logger.tagged("cart") do
      Binnacle.logger.info "Adding Item 123"
      Binnacle.logger.info "Adding Item 234"
    end
    render nothing: true
  end

  def multi_tagged
    Binnacle.logger.tagged("account", "payments") do
      Binnacle.logger.info 'Added new credit card of type VISA'
      Binnacle.logger.info 'Remove Paypal account'
    end
    render nothing: true
  end
end

app/controllers/webpush_controller.rb
class WebpushController < ApplicationController
  def index
    gon.push(user_email: current_user.email)
  end

  def trigger
    client = Binnacle::Client.new(ENV['BINNACLE_API_KEY'], ENV['BINNACLE_API_SECRET'])
    client.signal_asynch(ENV['BINNACLE_WP_CHANNEL'], 'push_one',
                                               current_user.email,
                                               '',
                                               'INFO',
                                               [],
                                               { user: current_user.name })
  end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController

  before_action :initialize_binnacle_chat, only: :chat

  def chat; end

  def arcud
    @articles = Article.all
  end

  def notifications; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def host
    Rails.env.development? ? 'http://localhost:5000' : 'https://binnacle.io'
  end

  def application_log
    if ENV['BINNACLE_ACCT_ID'] && ENV['BINNACLE_APP_ID']
      "#{host}/accounts/#{ENV['BINNACLE_ACCT_ID']}/apps/#{ENV['BINNACLE_APP_ID']}/log"
    else
      nil
    end
  end

  def logging_channel_log
    if ENV['BINNACLE_ACCT_ID'] && ENV['BINNACLE_APP_ID'] && ENV['BINNACLE_APP_LOG_CHANNEL_ID']
      "#{host}/accounts/#{ENV['BINNACLE_ACCT_ID']}/apps/#{ENV['BINNACLE_APP_ID']}/channels/#{ENV['BINNACLE_APP_LOG_CHANNEL_ID']}/log"
    else
      nil
    end
  end

  def error_channel_log
    if ENV['BINNACLE_ACCT_ID'] && ENV['BINNACLE_APP_ID'] && ENV['BINNACLE_APP_ERR_CHANNEL_ID']
      "#{host}/accounts/#{ENV['BINNACLE_ACCT_ID']}/apps/#{ENV['BINNACLE_APP_ID']}/channels/#{ENV['BINNACLE_APP_ERR_CHANNEL_ID']}"
    else
      nil
    end
  end

  def edit_app
    if ENV['BINNACLE_ACCT_ID'] && ENV['BINNACLE_APP_ID']
      "#{host}/accounts/#{ENV['BINNACLE_ACCT_ID']}/apps/#{ENV['BINNACLE_APP_ID']}/edit"
    else
      nil
    end
  end

end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/views/articles/_articles.html.erb
<h2>Articles</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody id="articles">
    <% @articles.each do |article| %>
      <tr id="article-<%= article.id %>">
        <td><%= article.title %></td>
        <td><%= article.text %></td>
        <td><%= link_to 'Edit', edit_article_path(article), remote: true %></td>
        <td><%= link_to 'Destroy', article, method: :delete, remote: true, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path, remote: true, class: "btn" %>
<div id="article-modal" class="modal fade"></div>

app/views/articles/_edit.html.erb
<div class="modal-dialog">
  <%= form_for(@article, remote: true, html: { class: "form-horizontal", style: "display:inline;" }) do |f| %>
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Edit Article</h4>
      </div>
      <%= render partial: "form", locals: {f: f} %>
    </div><!-- /.modal-content -->
  <% end %>
</div><!-- /.modal-dialog -->

app/views/articles/_form.html.erb
<div class="modal-body">
  <ul class="errors"></ul>
  <div class="control-group">
    <%= f.label :title, class:"control-label" %>
    <div class="controls">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :text, class: "control-label" %>
    <div class="controls">
      <%= f.text_area :text, class: "form-control" %>
    </div>
  </div>
</div>
<div class="modal-footer">
  <%= f.submit class: "btn btn-primary" %>
  <%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
</div>

app/views/articles/_new.html.erb
<div class="modal-dialog">
  <%= form_for(@article, remote: true, html: { class: "form-horizontal", style: "display:inline;" }) do |f| %>
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">New Article</h4>
      </div>
      <%= render partial: "form", locals: {f: f} %>
    </div><!-- /.modal-content -->
  <% end %>
</div><!-- /.modal-dialog -->

app/views/articles/create.js.erb
$.Article.addArticle(<%= raw(@article.to_json) %>);
$("#article-modal").modal("hide");

app/views/articles/edit.js.erb
$("#article-modal").html("<%= escape_javascript(render 'edit') %>")
$("#article-modal").modal("show")

app/views/articles/new.js.erb
$("#article-modal").html("<%= escape_javascript(render 'new') %>")
$("#article-modal").modal("show")

app/views/articles/update.js.erb
$.Article.updateArticle(<%= raw(@article.to_json) %>);
$("#article-modal").modal("hide");

app/views/candidates/reset_votes_for.js.erb
$.notify({
  icon: 'fa fa-check-circle',
  title: '<strong>Reset</strong>',
  message: "You've reset your votes!"
})

app/views/candidates/vote.js.erb
$.notify({
  icon: 'fa fa-check-circle',
  title: '<strong>You voted</strong>',
  message: 'Thanks for you vote!'
})

app/views/exceptions/index.html.erb
<section class="intro">
  <div class="container">
    <div class="row text-center">
      <div class="col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2">
        <%= image_tag('exception-signal.svg', class: "img-responsive") %>
        <h1>Exception to Signal</h1>
      </div>
    </div> <!-- /row -->
  </div> <!-- /container -->
</section> <!-- /intro -->
<section class="content">
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <p>Binnacle can generate signal is response to exceptions thrown by your Rails application.</p>
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title">Tail the Log</h3>
          </div>
          <div class="panel-body">
            <p>You can view the error channel (<strong><%= ENV['BINNACLE_APP_ERR_CHANNEL'] %></strong>) where exceptions are summarized.</p>

          <% if error_channel_log %>
            <%= link_to(error_channel_log, class: 'btn btn-primary', target: 'blank') do %>
              <i class="fa fa-external-link"></i> Open Errors View
            <% end %>
          <% end %>
          </div> <!-- /panel-body -->
        </div> <!-- /panel -->
        <h2>Exception Trapping</h2>
        <p>The code below triggers one of ten different exceptions, use the <strong>'Try it!'</strong> button to send a signal to Binnacle:</p>
        <figure class="highlight">
          <div class="zero-clipboard">
            <%= button_to "Try it!", trigger_exception_path, remote: true, class: "btn-clipboard", data: { container: "body", toggle: "popover", trigger: "hover", placement:"left", title: "Try it!", content: "Trigger an exception and watch them reported on binnacle.io"} %>
          </div>
<pre class="prettyprint">def trigger
  random_choice = 1 + rand(10)
  case random_choice
  when 1
    1 / 0
  when 2
    [1, 2, 3].first("two")
  when 3
    eval("1+1=2")
  when 4
    "hello".to_ary
  when 5
    [1, 2, 3].first(4, 5)
  when 6
    Float::INFINITY.to_r
  when 7
    puts foo
  when 8
    Regexp.new("?")
  when 9
    [1, 2, 3].drop(1 << 100)
  when 10
    h = {}
    h.fetch("baz") #=> KeyError: key not found: "baz"
  end
end</pre>
        </figure>
      </div>
    </div> <!-- /row -->
  </div> <!-- /container -->
</section> <!-- /content -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Binnacle Sample App</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
  <%= Gon::Base.render_data %>

  <!-- google font libraries -->
	<link href='//fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>
  <link href='//fonts.googleapis.com/css?family=Roboto+Condensed:400' rel='stylesheet' type='text/css'>
	<link href='//fonts.googleapis.com/css?family=Source+Code+Pro:500' rel="stylesheet">

  <%= yield :binnacle_chat %>
  <%= javascript_include_tag 'highcharts', 'chartkick' %>
  <link rel="manifest" href="/manifest.json" />

  <!-- Favicon -->
  <link rel="shortcut icon" type="image/x-icon" href="<%= asset_path 'favicon.ico' %>">
</head>
<body role="document" class="binnacle <%= "#{params[:controller]}_#{params[:action]}" %>">
  <header class="navbar-fixed-top">
		<div class="container">
			<div class="row flex-center">
        <div class="col-md-3 col-md-offset-1 col-sm-5 col-xs-8">
  				<a href="/" class="logo flex-center">
  					<%= image_tag('logo.svg', class: "img-responsive") %>
            <span>Showcase</span>
  				</a>
        </div>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="collapse navbar-collapse text-right navbar-nav" id="nav">
          <ul class="list-unstyled list-inline">
            <li class="dropdown">
              <a href="#" class="<%= 'active' if current_page?(webpush_path) || current_page?(page_path('configuration')) %> dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Start <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li class="<%= 'active' if current_page?(home_path) %>"><%= link_to( 'Welcome', home_path) %></li>
                <li class="<%= 'active' if current_page?(page_path('configuration')) %>"><%= link_to 'Configuration', page_path('configuration') %></li>
              </ul>
            </li> <!-- /dropdown -->
            <%- if user_signed_in? %>
            <li class="<%= 'active' if current_page?(webpush_path) %>"><%= link_to('Web Push', webpush_path) %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Signalling <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li class="<%= 'active' if current_page?(logging_path) %>"><%= link_to('Log to Signal', logging_path) %></li>
                <li class="<%= 'active' if current_page?(exceptions_path) %>"><%= link_to('Exception to Signal', exceptions_path) %></li>
              </ul>
            </li>
            <li class="<%= 'active' if current_page?(candidates_path) %>"><%= link_to 'Realtime', candidates_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Widgets <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to('AR Cud', arcud_path) %></li>
                <li><%= link_to('Chat Widget', chat_path) %></li>
                <!-- li><%#= link_to('Notifications', notifications_path) %></li -->
              </ul>
            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to('Sign Out', destroy_user_session_path, method: :delete) %></li>
              </ul>
            </li>
            <% else %>
            <li><%= link_to('Sign Up', new_user_registration_path) %></li>
            <li><%= link_to('Log In', new_user_session_path) %></li>
            <% end %>
          </ul>
        </div>
      </div> <!-- /row -->
		</div> <!-- /container -->
	</header>
  <!-- Fixed navbar -->
  <!-- <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to('Binnacle Showcase', home_path, class: 'navbar-brand') %>
      </div> -->
      <!-- <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="dropdown">
            <a href="#" class="<%= 'active' if current_page?(webpush_path) || current_page?(page_path('configuration')) %> dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Getting Started <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li class="<%= 'active' if current_page?(home_path) %>"><%= link_to( 'Welcome', home_path) %></li>
              <li class="<%= 'active' if current_page?(page_path('configuration')) %>"><%= link_to 'Configuration', page_path('configuration') %></li>
            </ul>
          </li>

          <%- if user_signed_in? %> -->
          <!--li class="<%= 'active' if current_page?(page_path('configuration')) %>"><%= link_to 'Configuration', page_path('configuration') %></li -->
          <!-- <li class="<%= 'active' if current_page?(webpush_path) %>"><%= link_to('Web Push', webpush_path) %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Ways to Signal <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li class="<%= 'active' if current_page?(logging_path) %>"><%= link_to('Log to Signal', logging_path) %></li>
              <li class="<%= 'active' if current_page?(exceptions_path) %>"><%= link_to('Exeption to Signal', exceptions_path) %></li>
            </ul>
          </li>
          <li class="<%= 'active' if current_page?(candidates_path) %>"><%= link_to 'Realtime', candidates_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Widgets <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to('AR Cud', arcud_path) %></li>
              <li><%= link_to('Chat Widget', chat_path) %></li> -->
              <!-- li><%#= link_to('Notifications', notifications_path) %></li -->
            <!-- </ul>
          </li>
          <% end %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <%- if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to('Sign Out', destroy_user_session_path, method: :delete) %></li>
            </ul>
          </li>
          <% else %>
          <li><%= link_to('Sign In', new_user_session_path) %></li>
          <li><%= link_to('Sign Up', new_user_registration_path) %></li>
          <% end %>
        </ul> -->
      <!-- </div>
    </div>
  </nav> -->

  <%= yield %>

  <!-- Bootstrap core JavaScript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <%= javascript_include_tag 'application' %>
</body>
</html>

app/views/logging/index.html.erb
<section class="intro">
  <div class="container">
    <div class="row text-center">
      <div class="col-md-8 col-md-offset-2 col-xs-8 col-xs-offset-2">
        <%= image_tag('log-signal.svg', class: "img-responsive") %>
        <h1>Log to Signal</h1>
      </div>
    </div> <!-- /row -->
  </div> <!-- /container -->
</section> <!-- /intro -->
<section class="content">
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <p>Binnacle can log incoming or outgoing HTTP requests from your application. You can also use the Binnacle Logger directly to send signals to Binnacle. The Binnacle Logger conforms to the <a href="http://ruby-doc.org/stdlib-2.3.0/libdoc/logger/rdoc/Logger.html" target="blank">Ruby Logger class</a>.</p>
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3 class="panel-title">Tail the Log</h3>
          </div>
          <div class="panel-body">
            <p>You can open the log tail view for the channel (<strong><%= ENV['BINNACLE_APP_LOG_CHANNEL'] %></strong>) used for general logging or view the aggregated logs for the application (<strong><%= ENV['BINNACLE_APP'] %></strong>) to see the signals generated by the logging statements below.</p>
            <% if application_log %>
              <%= link_to(application_log, class: 'btn btn-primary', target: 'blank') do %>
                <i class="fa fa-external-link"></i> Open App Log Viewer
              <% end %>
            <% end %>

            <% if logging_channel_log %>
              <%= link_to(logging_channel_log, class: 'btn btn-primary', target: 'blank') do %>
                <i class="fa fa-external-link"></i> Open Channel Log Viewer
              <% end %>
            <% end %>
          </div> <!-- /panel-body -->
        </div> <!-- /panel -->
        <h2>Basic Logging</h2>
        <p>The binnacle logger can be used just like any other Ruby Logger. You can access it via the class method logger in the Binnacle module:</p>
        <figure class="highlight">
          <div class="zero-clipboard">
            <%= button_to "Try it!", logging_info_path, remote: true, class: "btn-clipboard", data: { container: "body", toggle: "popover", trigger: "hover", placement:"left", title: "Try it!", content: "Trigger the logging statements and watch them live on binnacle.io"} %>
          </div>
<pre class="prettyprint">Binnacle.logger.info("This is an info message")</pre>
        </figure>
        <h2>Log Levels</h2>
        <p>Set the logger's level with <code>Binnacle.logger.level = Logger::DEBUG</code>:</p>
        <figure class="highlight">
          <div class="zero-clipboard">
            <%= button_to "Try it!", logging_debug_path, remote: true, class: "btn-clipboard", data: { container: "body", toggle: "popover", trigger: "hover", placement:"left", title: "Try it!", content: "Trigger the logging statements and watch them live on binnacle.io"} %>
          </div>
<pre class="prettyprint">Binnacle.logger.level = Logger::DEBUG
Binnacle.logger.debug("This is an debug message")</pre>
        </figure>
        <h2>Using Progname</h2>
        <p>Use the progname attribute to change the name of the event being logged.</p>
        <p>By default Binnacle uses <code>log</code> as the event name:</p>
        <p>Passing a String will override the event name.</p>
        <figure class="highlight">
          <div class="zero-clipboard">
            <%= button_to "Try it!", logging_with_procname_path, remote: true, class: "btn-clipboard", data: { container: "body", toggle: "popover", trigger: "hover", placement:"left", title: "Try it!", content: "Trigger the logging statements and watch them live on binnacle.io"} %>
          </div>
<pre class="prettyprint">Binnacle.logger.level = Logger::ERROR
Binnacle.logger.error('comm_error') { "Can't reach the service endpoint!" }</pre>
        </figure>
        <h2>Using Progname Hash</h2>
        <p>Passing a Hash as the progname parameter you can then specify a Binnacle's signal remaining parameters (session_id, event_name, client_id, tags):</p>
        <figure class="highlight">
          <div class="zero-clipboard">
            <%= button_to "Try it!", logging_with_procname_hash_path, remote: true, class: "btn-clipboard", data: { container: "body", toggle: "popover", trigger: "hover", placement:"left", title: "Try it!", content: "Trigger the logging statements and watch them live on binnacle.io"} %>
          </div>
<pre class="prettyprint">Binnacle.logger.info(channel_id: '<%= ENV['BINNACLE_APP_LOG_CHANNEL'] %>', session_id: '8675309', event_name: 'failed_transfer') {
  'transfer failed, bad RTN'
}</pre>
        </figure>
        <h2>Tagged Logging</h2>
        <p>Tagged Logging can be used to apply a tag to a set of logging statements:</p>
        <figure class="highlight">
          <div class="zero-clipboard">
            <%= button_to "Try it!", logging_tagged_path, remote: true, class: "btn-clipboard", data: { container: "body", toggle: "popover", trigger: "hover", placement:"left", title: "Try it!", content: "Trigger the logging statements and watch them live on binnacle.io"} %>
          </div>
<pre class="prettyprint">Binnacle.logger.tagged("cart") do
  Binnacle.logger.info "Adding Item 123"
  Binnacle.logger.info "Adding Item 234"
end</pre>
        </figure>
        <h2>Multiple Tags</h2>
        <p>You can pass multiple tags to a Tagged Logging statement:</p>
        <figure class="highlight">
          <div class="zero-clipboard">
            <%= button_to "Try it!", logging_multi_tagged_path, remote: true, class: "btn-clipboard", data: { container: "body", toggle: "popover", trigger: "hover", placement:"left", title: "Try it!", content: "Trigger the logging statements and watch them live on binnacle.io"} %>
          </div>
<pre class="prettyprint">Binnacle.logger.tagged("account", "payments") do
  Binnacle.logger.info 'Added new credit card of type VISA'
  Binnacle.logger.info 'Remove Paypal account'
end</pre>
        </figure>
      </div>
    </div> <!-- /row -->
  </div> <!-- /container -->
</section> <!-- /content -->